/// <reference types="next" />
/// <reference types="next/image-types/global" />

<<<<<<< HEAD
// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/building-your-application/configuring/typescript for more information.
=======
// This file is auto-generated by Next.js. Do not edit.
>>>>>>> 3d549590b8362e89faeb9c442c35a3d2fc36de6a
